'use strict';
//26/01/26

/* global barProperties:readable */
include('..\\helpers\\helpers_xxx.js');
/* global globFonts:readable, VK_CONTROL:readable, folders:readable, MK_SHIFT:readable */
include('..\\helpers\\buttons_xxx.js');
/* global getUniquePrefix:readable, buttonsBar:readable, addButton:readable, ThemedButton:readable, showButtonReadme:readable */
include('..\\helpers\\buttons_xxx_menu.js');
/* global settingsMenu:readable */
include('..\\helpers\\menu_xxx.js');
/* global _menu:readable, MF_STRING:readable, MF_GRAYED:readable */
include('..\\helpers\\helpers_xxx_prototypes.js');
/* global isBoolean:readable, isString:readable, isStringWeak:readable */
include('..\\helpers\\helpers_xxx_file.js');
/* global _foldPath:readable, _isFile:readable, _exec:readable, _recycleFile:readable, _resolvePath:readable, _save:readable */
include('..\\helpers\\helpers_xxx_UI.js');
/* global _gdiFont:readable, _gr:readable, _scale:readable */
include('..\\helpers\\helpers_xxx_properties.js');
/* global setProperties:readable, getPropertiesPairs:readable */

var prefix = 'chk'; // NOSONAR[global]

if (!window.ScriptInfo.Name) { window.DefineScript('Checksum Tools Button', { author: 'regorxxx', features: { drag_n_drop: false } }); }

prefix = getUniquePrefix(prefix, ''); // Puts new ID before '_'

var newButtonsProperties = { // NOSONAR[global]
	bIconMode: ['Icon-only mode', false, { func: isBoolean }],
	binPath: ['Binary path', (_isFile(folders.binaries + 'fsum\\fsum.exe')
		? _foldPath(folders.binaries)
		: folders.xxxRootName + 'helpers-external\\'
	) + 'fsum\\fsum.exe', { func: isStringWeak }],
	binCalcArgs: ['Checksum calculation arguments', '-crc32 -js -jnc -s -r -d"%1" *.*', { func: isString }],
	binCheckArgs: ['Checksum verification arguments', '-c -js -jf -d"%1" "%2"', { func: isString }],
	checkExt: ['Checksum file extension', '.sfv', { func: isString }],
	bOverwrite: ['Overwrite existing checksum', true, { func: isBoolean }],
	bReportOnCalc: ['Show report on calculation', false, { func: isBoolean }],
};
Object.keys(newButtonsProperties).forEach(p => newButtonsProperties[p].push(newButtonsProperties[p][1]));
setProperties(newButtonsProperties, prefix, 0); //This sets all the panel properties at once
newButtonsProperties = getPropertiesPairs(newButtonsProperties, prefix, 0);
buttonsBar.list.push(newButtonsProperties);

addButton({
	'Checksum Tools': new ThemedButton({
		coordinates: { x: 0, y: 0, w: _gr.CalcTextWidth('Checksum Tools', _gdiFont(globFonts.button.name, globFonts.button.size * buttonsBar.config.scale)) + 25 * _scale(1, false) / _scale(buttonsBar.config.scale), h: 22 },
		text: 'Checksum Tools',
		func: function (mask) {
			if (mask === MK_SHIFT) {
				const menu = settingsMenu(this, true, ['buttons_utils_crc.js.js']);
				menu.btn_up(this.currX, this.currY + this.currH);
			} else {
				// Menu
				const menu = new _menu();
				menu.newEntry({
					entryText: 'Create checksum per dir', func: () => {
						this.switchAnimation('Checksum Tools processing selection', true);
						this.bRunning = true;
						const header = '; Generated by WIN-SFV32 v1.0\r\n' + '; (Compatible: Total Commander 11.50)\r\n';
						const handleList = fb.GetSelections(1);
						if (handleList && handleList.Count) {
							handleList.Sort();
							const paths = [...new Set(fb.TitleFormat('$directory_path(%PATH%)').EvalWithMetadbs(handleList))];
							this.switchAnimation('Checksum Tools processing selection', false);
							Promise.serial(paths, (path, i) => {
								const animId = 'Checksum Tools processing folder ' + (i + 1) + '/' + paths.length;
								this.switchAnimation(animId, true);
								const idx = path.lastIndexOf('\\');
								const file = idx !== -1 ? path.slice(idx + 1) : 'checksum';
								const filePath = path + '\\' + file + this.buttonsProperties.checkExt[1];
								if (this.bAbort) { return { path, file, checksum: null, overwritten: false, saved: false }; }
								const bFound = _isFile(filePath);
								if (bFound && !this.buttonsProperties.bOverwrite[1]) { return { path, file, checksum: null, overwritten: false, saved: false }; }
								const overwritten = bFound ? _recycleFile(filePath) : false;
								return _exec(_resolvePath(this.buttonsProperties.binPath[1]) + ' ' + this.buttonsProperties.binCalcArgs[1].replaceAll('%1', path))
									.then((checksum) => {
										this.switchAnimation(animId, false);
										if (checksum && checksum.length) {
											checksum = header + checksum;
											const saved = _save(filePath, checksum);
											console.log('Checksum Tools: ' + file);
											return { path, file, checksum, overwritten, saved };
										}
										return { path, file, checksum: null, overwritten: false, saved: false };
									});
							}).then((results) => {
								let report = 'Checksum Tools:\n';
								if (this.bAbort) { report += '\tProcessing was aborted\n'; }
								report += '\t' + results.length + ' processed folders';
								report += '\t' + results.filter((r) => r.checksum === null).length + ' skipped folders';
								report += '\n';
								report += '\t' + results.filter((r) => r.saved).length + ' saved files';
								report += '\t\t' + results.filter((r) => r.overwritten).length + ' overwritten files';
								console.log(report);
								if (this.buttonsProperties.bReportOnCalc[1] || this.bAbort || results.some((r) => r.checksum && !r.saved)) {
									report += '\n\n' + results.map((r) => r.path + '\\' +  r.file + this.buttonsProperties.checkExt[1] + ' - ' + (r.saved ? 'saved' : (r.checksum === null ? 'skipped' : 'error'))).join('\n');
									fb.ShowPopupMessage(report);
								}
							}).finally(() => {
								this.bRunning = this.bAbort = false;
								this.stopAllAnimations();
							});
						} else {
							this.bRunning = this.bAbort = false;
							this.stopAllAnimations();
						}
					}, flags: this.bRunning ? MF_GRAYED : MF_STRING
				});
				menu.newEntry({
					entryText: 'Verify checksum per dir', func: () => {
						this.switchAnimation('Checksum Tools processing selection', true);
						this.bRunning = true;
						const handleList = fb.GetSelections(1);
						if (handleList && handleList.Count) {
							handleList.Sort();
							const paths = [...new Set(fb.TitleFormat('$directory_path(%PATH%)').EvalWithMetadbs(handleList))];
							this.switchAnimation('Checksum Tools processing selection', false);
							Promise.serial(paths, (path, i) => {
								const animId = 'Checksum Tools verifying folder ' + (i + 1) + '/' + paths.length;
								this.switchAnimation(animId, true);
								const idx = path.lastIndexOf('\\');
								const file = idx !== -1 ? path.slice(idx + 1) : 'checksum';
								const filePath = path + '\\' + file + this.buttonsProperties.checkExt[1];
								if (this.bAbort) { return { path, file, pass: false, errors: null }; }
								const bFound = _isFile(filePath);
								if (!bFound) { return { path, file, pass: false, errors: null }; }
								return _exec(_resolvePath(this.buttonsProperties.binPath[1]) + ' ' + this.buttonsProperties.binCheckArgs[1].replaceAll('%1', path).replaceAll('%2', filePath))
									.then((out) => {
										this.switchAnimation(animId, false);
										if (out && out.length) {
											const errors = out.count('\n');
											console.log('Checksum Tools: ' + file + this.buttonsProperties.checkExt[1] + ' - ' + errors + ' errors found');
											return { path, file, pass: false, errors };
										}
										console.log('Checksum Tools: ' + file + this.buttonsProperties.checkExt[1]);
										return { path, file, pass: true, errors: 0 };
									});
							}).then((results) => {
								let report = 'Checksum Tools:\n';
								if (this.bAbort) { report += '\tProcessing was aborted\n'; }
								report += '\t' + results.length + ' processed folders';
								report += '\t' + results.filter((r) => r.errors === null).length + ' skipped folders';
								report += '\n';
								report += '\t' + results.filter((r) => r.pass).length + ' passed';
								report += '\t\t\t' + results.filter((r) => r.errors).length + ' errors';
								console.log(report);
								report += '\n\n' + results.map((r) => r.path + '\\' +  r.file + this.buttonsProperties.checkExt[1] + ' - ' + (r.errors ? r.errors + ' errors' : 'passed')).join('\n');
								fb.ShowPopupMessage(report);
							}).finally(() => {
								this.bRunning = this.bAbort = false;
								this.stopAllAnimations();
							});
						} else {
							this.bRunning = this.bAbort = false;
							this.stopAllAnimations();
						}
					}, flags: this.bRunning ? MF_GRAYED : MF_STRING
				});
				menu.newSeparator();
				menu.newEntry({
					entryText: 'Abort processing', func: () => {
						this.bAbort = true;
					}, flags: this.bRunning ? MF_STRING : MF_GRAYED
				});
				menu.newSeparator();
				menu.newEntry({ entryText: 'Settings...', func: () => this.onClick(MK_SHIFT) });
				menu.newSeparator();
				menu.newEntry({ entryText: 'Open readme...', func: () => showButtonReadme('buttons_utils_autobackup.js') });
				menu.btn_up(this.currX, this.currY + this.currH);
			}
		},
		description: function () {
			const bCtrl = utils.IsKeyPressed(VK_CONTROL);
			const bInfo = typeof barProperties === 'undefined' || barProperties.bTooltipInfo[1];
			let info = 'Checksum tools for library:';
			// Entries
			if (bCtrl || bInfo) {
				info += '\n-----------------------------------------------------';
				info += '\n(Ctrl + L. Click to Save && Backup on demand)';
			}
			return info;
		},
		prefix, buttonsProperties: newButtonsProperties,
		icon: '\uf1ec',
		variables: {
			bAbort: false,
			bRunning: false,
		}
	})
});